### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by WangHoHan** [WangHoHan/safe-notebook#1]
- [ ] encrypt memo with key
- [ ] high entropy random number generator (isaac?)
- [x] biometrics
- [x] check root access (biometrics)
- [x] generate key after biometrics authentication
- [ ] wipe data after few mistakes
